language: java

before_install:
  - chmod +x gradlew

jdk:
  - oraclejdk9

script:
  - ./gradlew build --scan -s

deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app:  usuarios-api-demo
